### ISSUE TITLE
Remote Controller completely frozen

### ISSUE THREAD

**Issue by dieter-struck** [SKAARHOJ/skaarhoj-updater-releases#14]
Background Issue: 
      
```
Error: Object has been destroyed
    at WebContents.send (/Applications/SKAARHOJUpdater.app/Contents/Resources/electron.asar/browser/api/web-contents.js:103:17)
    at /Applications/SKAARHOJUpdater.app/Contents/Resources/app.asar/background.js:16:329514
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

---

SKAARHOJUpdater 1.0.5
Electron 6.1.10
darwin 20.1.0
Locale: de

**Comment by dieter-struck** [comment]
After going into "Sleep Mode" Controller is frozen. Nothing is working anymore.
