### ISSUE TITLE
Updated the app : got this

### ISSUE THREAD

**Issue by ChristofferThinggaard** [SKAARHOJ/skaarhoj-updater-releases#17]
Background Issue: 
      
```
Error: dns service error: service not running
    at new Browser (C:\Users\chris\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\browser.js:88:10)
    at Object.create [as createBrowser] (C:\Users\chris\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\browser.js:116:10)
    at Timeout.ce [as _onTimeout] (C:\Users\chris\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\background.js:2:6932803)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

---

SKAARHOJUpdater 1.0.11-pre2
Electron 6.1.10
win32 10.0.19042
Locale: da

**Comment by s00500** [comment]
Duplicate #16
