### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by vibemasterer** [SKAARHOJ/skaarhoj-updater-releases#18]
Background Issue: 
      
```
Error: Object has been destroyed
    at WebContents.send (/Applications/SKAARHOJUpdater.app/Contents/Resources/electron.asar/browser/api/web-contents.js:103:17)
    at /Applications/SKAARHOJUpdater.app/Contents/Resources/app.asar/background.js:2:671117
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

---

SKAARHOJUpdater 1.0.10
Electron 6.1.10
darwin 20.6.0
Locale: en-GB

**Comment by s00500** [comment]
Hey @vibemasterer, can you provide some more information on this issue ? when did it happen ? can you reproduce it ?
Does it happen regulary for you ?
