### ISSUE TITLE
Error at install?

### ISSUE THREAD

**Issue by HakanUR** [SKAARHOJ/skaarhoj-updater-releases#2]
Background Issue: ```
Error: Cannot find latest.yml in the latest release artifacts (https://github.com/SKAARHOJ/skaarhoj-updater-releases/releases/download/v0.9.13/latest.yml): HttpError: 404 Not Found
"method: GET url: https://github.com/SKAARHOJ/skaarhoj-updater-releases/releases/download/v0.9.13/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Wed, 06 Nov 2019 09:41:25 GMT",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "server": "GitHub.com",
  "set-cookie": [
    "has_recent_activity=1; path=/; expires=Wed, 06 Nov 2019 10:41:25 -0000",
    "logged_in=no; domain=.github.com; path=/; expires=Sun, 06 Nov 2039 09:41:25 -0000; secure; HttpOnly",
    "_gh_sess=UUtXWG5xWDdtSmJlUW51b0tVTUI5UW1aRUl2ck1vTzBjYVNPYkFhWTZnUWpRNjNFSmd1dERPS2s5ME5ZdlNrazlGV2kwU2VHMmx3T1NybXMvcGFsSlpvOU1WcEVtb1M1OWx3YTRMTlJNWnFISkVLL2pWMDVidmxpN1pLUHFYTWxhL21ENk1XSnplWnRqbTdSNHo3eXAxWUt1UkEzNEtQbTYxN2dTYkF0VU1zPS0tOVBibytaNnAyNlRVMDh0QzNnL3hldz09--2ff706d03ecd9b30f5d0578cb9601b8d56188c79; path=/; secure; HttpOnly"
  ],
  "status": "404 Not Found",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "transfer-encoding": "chunked",
  "vary": "X-PJAX",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "2A04:14124:8A67EE8:CFE851C:5DC29545",
  "x-request-id": "a528a988-76f7-423f-a977-1aa560a31b81",
  "x-xss-protection": "1; mode=block"
}
    at p (C:\Users\hjn\AppData\Local\Programs\SKAARHOJUpdaterBeta\resources\app.asar\background.js:1:120378)
    at t.ElectronHttpExecutor.handleResponse (C:\Users\hjn\AppData\Local\Programs\SKAARHOJUpdaterBeta\resources\app.asar\background.js:1:121977)
    at ClientRequest.<anonymous> (C:\Users\hjn\AppData\Local\Programs\SKAARHOJUpdaterBeta\resources\app.asar\background.js:1:121446)
    at ClientRequest.emit (events.js:200:13)
    at URLRequest.<anonymous> (C:\Users\hjn\AppData\Local\Programs\SKAARHOJUpdaterBeta\resources\electron.asar\browser\api\net.js:221:18)
    at URLRequest.emit (events.js:200:13)
    at t.newError (C:\Users\hjn\AppData\Local\Programs\SKAARHOJUpdaterBeta\resources\app.asar\background.js:1:9048)
    at t.GitHubProvider.getLatestVersion (C:\Users\hjn\AppData\Local\Programs\SKAARHOJUpdaterBeta\resources\app.asar\background.js:1:155138)
```

---

SKAARHOJUpdaterBeta 0.9.12
Electron 6.0.12
win32 10.0.17763
Locale: sv

**Comment by s00500** [comment]
This should be fixed by now, just restart the application, thank you for reporting this issue!
