### ISSUE TITLE
PTZ FLY

### ISSUE THREAD

**Issue by SedonaUAS** [SKAARHOJ/skaarhoj-updater-releases#21]
Background Issue: 
      
```
Error: dns service error: service not running
    at new Browser (C:\Users\Sedon\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\browser.js:88:10)
    at Object.create [as createBrowser] (C:\Users\Sedon\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\browser.js:116:10)
    at Timeout.ce [as _onTimeout] (C:\Users\Sedon\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\background.js:2:6933573)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

---

SKAARHOJUpdater 1.0.11
Electron 6.1.10
win32 10.0.19042
Locale: en-US

**Comment by s00500** [comment]
Duplicate, please check the answer I provided in #20 

Hope this helps, Greetings
