### ISSUE TITLE
Error: getaddrinfo -3008

### ISSUE THREAD

**Issue by EugeneSakun** [SKAARHOJ/skaarhoj-updater-releases#23]
Background Issue: 
      
```
Error: getaddrinfo -3008
    at errnoException (/tmp/.mount_SKAARHt3Ka6J/resources/app.asar/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/tmp/.mount_SKAARHt3Ka6J/resources/app.asar/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/tmp/.mount_SKAARHt3Ka6J/resources/app.asar/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
```

---

SKAARHOJUpdater 1.0.11
Electron 6.1.10
linux 5.13.0-27-generic
Locale: en-US

**Comment by s00500** [comment]
Using sudo with the AppImage seems to be able to fix this, also the latest release improves the errorhandling so you can dismiss the error better
