### ISSUE TITLE
Error when launching Skaarhoj Updater

### ISSUE THREAD

**Issue by TVcameras** [SKAARHOJ/skaarhoj-updater-releases#26]
Background Issue: 
      
```
Error: dns service error: service not running
    at new Browser (C:\Users\pwrig\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\browser.js:88:10)
    at Object.create [as createBrowser] (C:\Users\pwrig\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\node_modules\mdns\lib\browser.js:116:10)
    at Timeout.ce [as _onTimeout] (C:\Users\pwrig\AppData\Local\Programs\SKAARHOJUpdater\resources\app.asar\background.js:2:6933573)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

---

SKAARHOJUpdater 1.0.11
Electron 6.1.10
win32 10.0.19042
Locale: en-US

**Comment by s00500** [comment]
Please check here: https://github.com/SKAARHOJ/skaarhoj-updater-releases/issues/20
