### ISSUE TITLE
My SKAARHOJ PTZ Pro V2 has an pixelated screen and won't start / update anymore

### ISSUE THREAD

**Issue by julianguttzeit** [SKAARHOJ/skaarhoj-updater-releases#33]
Background Issue: 
      
```
TypeError: Cannot read properties of null (reading 'write')
    at SerialPort.<anonymous> (/Applications/SKAARHOJUpdater.app/Contents/Resources/app.asar/background.js:2:540044)
    at SerialPort.emit (node:events:406:35)
    at binding.open.then.opening (/Applications/SKAARHOJUpdater.app/Contents/Resources/app.asar/node_modules/@serialport/stream/lib/index.js:234:12)
```

---

SKAARHOJUpdater 1.0.14
Electron 16.0.7
darwin 22.3.0
Locale: de
![IMG_0763](https://user-images.githubusercontent.com/11499702/233845822-15a4daae-e2cb-457a-9c0c-b363ff222159.JPG)
![IMG_0764](https://user-images.githubusercontent.com/11499702/233845829-9d687657-7866-4881-b662-0ddf7d1c200b.JPG)

**Comment by s00500** [comment]
Hi @julianguttzeit,

Can you maybe give a bit more explaination of what steps led to this ? do you have any more infos ?

Geht auch gerne auf Deutsch

MFG

**Comment by s00500** [comment]
In case you are still having issues please contact support@skaarhoj.com

issue stale, closing
